### ISSUE TITLE
WPRIG (uppercase) is not renamed

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#104]
## Issue Overview
If you add a constant, like `WPRIG_THEME_VERSION`, `WPRIG` is not replaced by an uppercase version of the theme's slug. 

## Expected Behavior
`WPRIG` should be replaced by the theme slug in uppercase.

## Current Behavior
`WPRIG` is not replaced.

**Comment by ataylorme** [comment]
@benoitchantre can you try the `v1.1` branch? THe process was overhauled in #93

**Comment by benoitchantre** [comment]
@ataylorme I did a merge on a work in progress project:

- PHP files look good (except errors from PHP CS, probably from my code)
- in navigation.js, I get the following error: `mythemeslugScreenReaderText is not defined`

**Comment by felixarntz** [comment]
@ataylorme I figured out why this happens: In `gulp/scripts.js`, the tasks only run if the relevant files have been edited since (via `gulpPlugins.newer`). This needs to be changed to also take into account whether the theme configuration has changed (see all the custom code currently part of `gulp/php.js`). Preferably, this should be added to `gulp/styles.js` as well - it doesn't matter at this point, but if someone added CSS classes prefixed with `wp-rig-` for example, they would run into the same issue.

@benoitchantre Until this is actually fixed, you should be able to workaround the issue by simply making a random change in the JavaScript file and saving, so that the time it was last updated is changed.

**Comment by ataylorme** [comment]
Thanks for identifying @felixarntz. `gulp-newer` allows you to check files outside the stream and, if they are newer than the destination files, to rebuild all files in the stream. I opened #123 to take advantage of this. A review when you can would be much appreciated.

**Comment by benoitchantre** [comment]
Thank you for the tip @felixarntz.

**Comment by mor10** [comment]
#123 is merged, so closing. Feel free to open if it still doesn't work.
