### ISSUE TITLE
Content width is not using $GLOBALS['content_width'] when set.

### ISSUE THREAD

**Issue by hellofromtonya** [wprig/wprig#12]
## Issue Overview
[In the function `wprig_content_width()`](https://github.com/wprig/wprig/blob/master/dev/functions.php#L175), code exists to assign the content's width from the global.  However, on the next line, the width is overwritten with a integer literal of 720:

```
function wprig_content_width() {

	if ( isset( $GLOBALS['content_width'] ) ) {
		$content_width = $GLOBALS['content_width'];
	}
	$content_width = 720;
```

## Expected Behavior
I would expect that we want this to be an either or assignment. Correct?  Either the global or the default.

## Current Behavior
720 is always assigned prior to the filter.

## Possible Solution

I'd propose refactoring the code like this:

```
function wprig_content_width() {

	$content_width = isset( $GLOBALS['content_width'] )
		? (int) $GLOBALS['content_width']
		: 720;
```

With this change, are doing the following:

1. If the global exists, we type cast it to integer and then assign it to the variable.
2. Else, we assign a default value of 720.

**Comment by mor10** [comment]
$cpmtent_width is a royal pain. has been for a long time. 

This is how it's currently handled at _s where they've been debating it for years:
https://github.com/Automattic/_s/blob/master/functions.php#L86-L99

On top of that comes Gutenberg which renders this feature more or less obsolete / requires it to change completely. Two relevant tickets:
https://github.com/WordPress/gutenberg/issues/5650
https://github.com/WordPress/gutenberg/issues/6177

I'm inclined to do nothing until Gutenberg sorts itself out because I have a feeling we might get a total rewrite of this entire feature. That said, I'm open to arguments to the contrary.

@hellofromtonya can you refactor your PR to be verbose? The ternary operator is clean, but it's also hard to understand for new/inexperienced developers. If/else statement would be better from a "what  is going on here" standpoint.

**Comment by hellofromtonya** [comment]
> I'm inclined to do nothing until Gutenberg sorts itself out because I have a feeling we might get a total rewrite of this entire feature.

Definitely could happen. 

>That said, I'm open to arguments to the contrary.

Right now, the code doesn't work as it is. Why? The global isn't being used at all.  It'll just be a point of confusion for those who build off of this theme.

That means we have a couple of choices:

1. Get it to work as it's designed, meaning if it's set, use it; else, use the default.
2. Make it like _s for commonality.
3. Or get rid of the global all together.

Thinking it through, it seems to me there is a reason why you wanted to use the global  if it was set.  Therefore, I'd vote that for now, we get it working.  Then when Gutenberg solidifies, we can revisit if we need to change it.

**Comment by hellofromtonya** [comment]
>@hellofromtonya can you refactor your PR to be verbose? The ternary operator is clean, but it's also hard to understand for new/inexperienced developers. If/else statement would be better from a "what is going on here" standpoint.

Done.  [You can view it here in PR #13](https://github.com/wprig/wprig/pull/13/commits/b3466d146e8e053ac2613cfca5b619eb92291f94#diff-8ab8775c3cc79aadce48cad633a7fde3R175).

**Comment by mor10** [comment]
The jetlag fog has lifted a bit and this makes sense. Unless @bamadesigner has any objections I'm recommending merge.

**Comment by bamadesigner** [comment]
I have it on my list to check out tomorrow. 👍🏻

**Comment by bamadesigner** [comment]
So, in core, the only place this global is used is in setting the embed width in `wp_embed_defaults()`.

So the more standard approach to solving this problem is simply to filter the 'embed_defaults' filter that's inside that function and set the width inside that filter, e.g.:

```
function wprig_embed_dimensions( $dimensions ) {
	$dimensions['width'] = 720;
	return $dimensions;
}
add_filter( 'embed_defaults', 'wprig_embed_dimensions', 10 );
```

Really, then we don't need the "wprig_content_width" filter because people can also use the 'embed_defaults' filter to achieve the same goal. Or we can move that filter here:

```
function wprig_embed_dimensions( $dimensions ) {
    $dimensions['width'] = apply_filters( 'wprig_content_width', 720 );
    return $dimensions;
}
add_filter( 'embed_defaults', 'wprig_embed_dimensions', 10 );
```

**Comment by mor10** [comment]
That makes a lot of sense @bamadesigner. It may also help us work around the inevitable Gutenberg mess which is coming down the track. What say you @hellofromtonya? Can you update your PR to do this new thing?

**Comment by hellofromtonya** [comment]
Excellent point, @bamadesigner! You are correct that we don't need a separate filter for the width and nor do we need to directly interact with the global either. 

I'll update the PR.

**Comment by hellofromtonya** [comment]
The only enhancement I'd offer is to type hint the incoming `$dimensions` parameter.
