### ISSUE TITLE
The v1.1 decision making issue

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#121]
This issue aims to answer two key questions:

1. When is v1.1 done (as in what features should / shouldn't be in 1.1)?
2. When are we merging v1.1 to master?

Your input is required.

**Comment by ataylorme** [comment]
+1 on the proposal. The timeline (2 weeks) may be a bit short to test all the things, surface bugs, fix those bugs, retest all the things, and get documentation updated.

**Comment by felixarntz** [comment]
I agree with the proposal, except that I share the @ataylorme's concern about timing. There are a couple of very critical issues around that we haven't stumbled across before, which to me indicates that we need to spend more time actually running and testing WP Rig than we've previously done. Based on that, I'm not sure whether 2 weeks are enough.

**Comment by ataylorme** [comment]
Thank you for the kind words @ev3rywh3re. You help with testing and reporting bugs is very much helpful and appreciated!

**Comment by mor10** [comment]
What do you think is a reasonable timeline? 3 weeks? A month?

**Comment by ataylorme** [comment]
> What do you think is a reasonable timeline? 3 weeks? A month?

Since this is such a big release I think we should:

- Decide what will be in `v1.1`. I link the proposal but is it formal?
- Assign testing tasks, perhaps broken up, to different folks
  - e.g. Felix for unit tests, myself for gulp, Morten and Rachel for overall
- Find out when each person can commit to testing their portion
- Set a date shortly after that to have all testing feedback and bugs recorded
- Asses and assign work for the feedback and bugs
- Determine a `v!.1` release candidate date
- Set a release date
- Do a final round of testing
- Release

**Comment by mor10** [comment]
Thank you @ataylorme. If it isn't clear, I have never run a large project like this before so this kind of input is extremely valuable. I'm thinking this is what the Projects feature is for?

**Comment by ataylorme** [comment]
Probably but the biggest concern for me personally, especially when working with volunteers, is burnout. I'm sure if we set a date 2 weeks out we could get it done. 

However, if that timeline puts too much stress on the folks contributing the benefit of releasing a few weeks sooner is not worth having unhappy contributors and less contributions going forward.

Maybe we can start with an estimate of availability each week for the next 6 weeks. Here is mine

- 9/23 - 9/29: up to 3 hours
- 9/30 - 10/6: up to 4 hours
- 10/7- 10/13: up to 6 hours
- 10/14 - 10/20: up to 3 hours
- 10/21 - 10/27: 1 hour or less
- 10/29 - 11/3: up to 2 hours

**Comment by felixarntz** [comment]
I can't currently provide a good estimate for the next couple weeks, but I should be able to dedicate about 6 hours next week.

About timeline, to me 4 weeks sounds like a more realistic goal. Maybe we will get it done in 2, and that'd be fine, but I agree having that as a timeline would be too stressful. I think it is most important at this point that we define what goes into 1.1, and for that I agree with @mor10 that after the SSL PR only bug fixes (and more tests) should be allowed for merging into it. Everything else would be milestoned for a later release.

**Comment by ataylorme** [comment]
Sounds like @mor10, @felixarntz and I are all on the same page about #92 being the last feature to go into `v1.1`. I consider #123 as a bug fix. I think we should aim to get those in next week and move forward with testing.

I would love to hear from @bamadesigner and @hellofromtonya as well.

**Comment by mor10** [comment]
The 2 week proposal was merely a proposal to get the conversation started. We need to take the necessary time to get this right while retaining our sanity and jobs and healthy family relations etc. Just sayin'.

**Comment by ataylorme** [comment]
I would like to add #123 to the discussion for consideration and possible inclusion in `v1.1`.

**Comment by felixarntz** [comment]
Given SemVer and the amount of major changes in `v1.1`, I'd like to bring up the idea of actually naming this `v2.0`. In that case especially I think #129 should be part of this release since that would bring us to a point where we have a solid base foundation to which we could then stay more backward-compatible than we have done so far.

Releasing a `v2.0` as next release after a `v1.0` might feel odd, but on the other hand, we've already discussed that we would need to tell folks who have been using `v1.0` that they'd need to perform several adjustments in order to migrate to `v1.1`. That alone indicates that maybe a major bump would make sense.

**Comment by mor10** [comment]
I'm tending toward the same thinking @felixarntz re moving to `v2.0` in place of `v1.1`. That would allow for #129 to be baked in and moves us a huge step forward.

To do this, we need a quorum. @bamadesigner @hellofromtonya please chime in.

**Comment by mor10** [comment]
Also, we need to think carefully about how we position #109 (BEM/CSS modules). If we say full core rework is `v2.0`, we can set the BEM/CSS modules rework as the goal for `v2.1` now and provide a clear development plan into the future.

**Comment by bamadesigner** [comment]
Hi all. Sorry for my absence. Disney just sucked away all my bandwidth but we launched! Yay!

I agree we can get #92 in for the next release.

I would say if we decide to do #129 we should bump up to v2.0 because big. 

With all that said, I say if we're going to do all this work we might as well try to knock out #129 and release v2.0. Unless I missed something, there's no rush here to get something out. Let's do it right and get that big change behind us so we can focus on more front-end details going forward. We've been focusing a lot on build tasks.

**Comment by mor10** [comment]
Closing in favor of #131 to start `v2.0` branch with a clean slate.
