### ISSUE TITLE
Widgets not showing in Customizer

### ISSUE THREAD

**Issue by thinnling** [wprig/wprig#126]
When I go to Widgets in Customizer it says:

`Your theme has 1 widget area, but this particular page doesn’t display it.
You can navigate to other pages on your site while using the Customizer to view and edit the widgets displayed on those pages.`

Even though I have widgets on all my pages.
I am on Win7, using latest version on VScode and have run `npm run build`.  
I cannot see it in Chrome, FireFox, or Opera.
Though, when I exit out of VScode and Gulp, and go to my site manually through localhost/wordpress, the Widget area is  in my Customiser and it's working correctly.  It just doesn't work when through VScode and after `npm run bild` is run.
I checked by reloading VScode, restarting my computer, clearing my browser and cache, used Sweep plugin.

So the problem is not with my Wordpress, it is with the Wp-rig build.

**Comment by mor10** [comment]
Customizer and BrowserSync do not play well together. As in at all. To use the Customizer, you have to open your development site from your local dev environment, not through BrowserSync. It's not something we can do anything about as it's caused by some sort of JavaScript conflict between BrowserSync and WordPress itself. It's weird.
