### ISSUE TITLE
How to change code standard?

### ISSUE THREAD

**Issue by shangdev** [wprig/wprig#149]
## Issue Overview
I want to use PSR2 as my code standard, How to do it?

I tried to change:
`
    .pipe(phpcs({
		bin: 'vendor/bin/phpcs',
		standard: 'WordPress',
		warningSeverity: 0
	}))
`
to
`
    .pipe(phpcs({
		bin: 'vendor/bin/phpcs',
		standard: 'PSR2',
		warningSeverity: 0
	}))
`

But it doesn't seem to work.

**Comment by felixarntz** [comment]
Thanks for opening this @shangdev!

I'd like to highlight that the WordPress coding standard is being used here for a good reason: It's not to enforce the actual WordPress code style guide across all projects because using PSR-2 is certainly fine (I use it myself for many projects). However, the WordPress coding standards include way more than that. They incorporate security best practices, performances best practices, accessibility best practices, and some best practices to WordPress specifically, while PSR-2 is really only about the code style. Therefore at this point it should not be replaced.

There are efforts on creating a coding standard that still leverages all these best practices in WordPress, but still uses PSR-2 for the style (see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1067). Until that is in place, PSR-2 should not be used in a WordPress project.
