### ISSUE TITLE
Gulp and Browser Sync Really Slow

### ISSUE THREAD

**Issue by caseydh** [wprig/wprig#155]
Hey guys,

I am new to Word Press, and am trying to pick it up as a tool because I have been picking up a lot of personal clients. WP Rig seemed like a pretty solid tool to use, so I am trying to learn it. However the gulp process is taking ages. I have used gulp and browser sync before they were never this slow. When I save a file it can take well over a minute to refresh the browser. I am not sure what is going on. Any suggestions would be greatly appreciated.

**Comment by felixarntz** [comment]
@ataylorme Just checking, might this be fixed by #133?

**Comment by ataylorme** [comment]
Yes, it should be much faster with the changes in #133.

**Comment by ataylorme** [comment]
@caseydh can you test the build speed in the [`v2.0 alpha`](https://github.com/wprig/wprig/tree/v2.0-alpha) version? Please note that there are some significant file structure and gulp changes.

It would probably be best to test in a new theme rather than attempt to apply the v2 updates to your existing WP Rig theme.

**Comment by mor10** [comment]
Fixed in `v2.0 alpha`, so I'm closing this issue. Feel free to open again.
