### ISSUE TITLE
Bump minumum PHP version to 7.1

### ISSUE THREAD

**Issue by benoitchantre** [wprig/wprig#175]
Security support for PHP 7.0 will end in 16 days (3 Dec 2018). I think WP Rig should discourage the use of unsupported PHP version.

**Comment by ataylorme** [comment]
[PHP `7.1` support](http://php.net/supported-versions.php) will also end at the end of this year. I think we should bump the required version to `7.2`.

cc @felixarntz and @mor10

**Comment by felixarntz** [comment]
I vote against this for now. Our code doesn't even use PHP 7.0 code yet (but soon it hopefully will #159). Bumping the minimum requirement IMO should happen on significant benefits that such a bump would introduce. WordPress core obviously does a terrible job at bumping PHP (not bumping despite tons of reasons for doing so), but by just doing the exact opposite (always bumping to the latest version despite lack of reasons) I don't think we're gonna get anywhere.

Again, updating PHP is hard for the average WordPress user, and we want themes built on WP Rig be usable by the masses - otherwise it won't have a measurable impact on the ecosystem outside of the more engaging, inner WordPress bubble of people.

**Comment by felixarntz** [comment]
I'd be in favor of clarifying though that 7.0 is a minimum requirement - it is not recommended. I think we should change `PHP 7.0` under requirements to `PHP 7.3 (recommended) or at least PHP 7.0 (minimum required)`

**Comment by ataylorme** [comment]
I think instead of specifying PHP 7.3 we should suggest the latest stable version of PHP and link to http://php.net/supported-versions.php
