### ISSUE TITLE
`the_attachment_navigation()` prints output even when there are no adjacent images

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#184]
The output should only be generated when it actually serves a purpose. Currently it will always be added even when there are no adjacent images.

Due to the expensiveness of this operation, the WP core restrictions to easily discover whether that output is needed or not, and the lack of incentive to even handle attachment pages on most sites (due to negative SEO implications, Yoast SEO disables these entirely for example), I'm even inclined to say we should get rid of this feature entirely

**Comment by mor10** [comment]
Attachment pages have significant value, and being able to navigate between them is essential. The problem here, from my perspective, is lack of support from WP core and theme developers not utilizing this feature effectively. Rather than remove the feature, we should push for better support in core so the process is not so expensive.

**Comment by felixarntz** [comment]
I have since reversed my opinion. Instead, the PR for granular template parts #244 actually fixes the problem that the output is unconditionally printed. :)

Also better core support is on its way hopefully (see https://core.trac.wordpress.org/ticket/45708).
