### ISSUE TITLE
Write a documentation Wiki post on CSS file organization

### ISSUE THREAD

**Issue by mor10** [wprig/wprig#277]
- Why CSS is split into separate files
- how to call CSS files from within templates
- how to preload CSS files if required

**Comment by felixarntz** [comment]
Similar documentation issues in other areas (for reference): #284, #285

**Comment by mor10** [comment]
Looks like @kevinwhoffman will be taking this on.

**Comment by kevinwhoffman** [comment]
@mor10 Yes, you can assign to me. I have been working to improve my understanding of the CSS techniques within WP Rig so that I can communicate how and why they are in place.

## Status Update
 
Over the past week I have:

- Tested the `v2.0` branch locally while step-through debugging the process of enqueuing and preloading stylesheets.
- Researched the origins and current state of Progressive CSS techniques.
- Researched how these techniques fit within the existing WordPress paradigm of registered/enqueued stylesheets.

### Discussion with Andrew Nacin Regarding `wp_print_styles`

I was initially concerned that the [Codex page for `wp_print_styles`](https://codex.wordpress.org/Plugin_API/Action_Reference/wp_print_styles) was recommending that it not be used:

> Since WordPress 3.3 wp_print_styles should not be used to enqueue styles or scripts.

The Codex cited [Nacin's article](https://make.wordpress.org/core/2011/12/12/use-wp_enqueue_scripts-not-wp_print_styles-to-enqueue-scripts-and-styles-for-the-frontend/) from the 3.3 release as a reason for not using `wp_print_styles`.

I reached out to Andrew Nacin [via Twitter](https://twitter.com/kevinwhoffman/status/1088521459696365570) to see if he had an updated opinion. Nacin clarified that both the Codex and his article were recommending against the action `wp_print_styles`, not the function `wp_print_styles()`.

In summary, the use of `wp_print_styles()` to print `<link>` elements in body looks like it should work well within WordPress. I will be sure to clarify the difference between the action and function in documentation.

### Concern Over Customizer CSS

Carolina Nymark brought up [a valid concern](https://twitter.com/carolinapoena/status/1088581891618471941) regarding printing stylesheet links in body:

> It does make it harder to overwrite the CSS. The content of the "Additional CSS" customizer option is output in the header by default.

Since Customizer CSS is printed in the `<head>`, it would become more difficult for users to override the CSS of a plugin or theme using the same selectors since the in-body stylesheets would appear later. Users would have to make sure the selectors they use to override CSS have greater specificity than the selectors they are overriding.

We should think about possible workarounds or at least documenting the need for greater specificity when overriding WP Rig component styles.

### Additional Research

- ["The future of loading CSS" by Jake Archibald](https://jakearchibald.com/2016/link-in-body/)
- ["CSS and Network Performance" by Harry Roberts](https://csswizardry.com/2018/11/css-and-network-performance/)
- ["Introduction to Resilient CSS" by Jen Simmons](https://www.youtube.com/watch?v=u00FY9vADfQ&list=PLbSquHt1VCf1kpv9WRGMCA9_Nn4vCLZ9Y)
- ["In-body modular style sheets" by Morten Rand-Hendriksen](https://wprig.io/learn/in-body-modular-style-sheets/?fbclid=IwAR2Z7y6k9QT_XTw6NqkRBQT7g42_e1JWyYEbaR5q-Uu9jkZvxmyvi0MCTfI)
- ["Loading just-in-time CSS in the Body with WordPress" by David Greenwald](https://www.rawkblog.com/2019/01/loading-just-in-time-css-in-the-body-with-wordpress/?fbclid=IwAR3kiEZmWZcYC2DHFGZSUNDVaC7L61Leks4nM-B7FpZ8fgBkhHBX7CPvqlg)
- ["A better, faster approach to CSS in WordPress themes" by Jono Alderson](https://developer.yoast.com/a-better-faster-approach-to-css-in-wordpress-themes/?fbclid=IwAR3o6UDP3CT7HiLE_VaeK2LATCcOnZS7DxrdAzR1ugxQ3UH2X_TpUBlXCWc)

**Comment by felixarntz** [comment]
See #319 for a related change, that once merged likely should be documented here too. It's not a major change, just adds more flexibility.

**Comment by mor10** [comment]
Wiki now features an extensive article on CSS in WP Rig v2.0, including file organization and other relevant info: https://github.com/wprig/wprig/wiki/CSS-in-WP-Rig
