### ISSUE TITLE
CSS variables are not resolved when using Sass

### ISSUE THREAD

**Issue by felixarntz** [wprig/wprig#316]
When using Sass, the CSS variables are not resolved to actual values in them, ignoring `preserveCSSVars: false` in the config.

That is because the Gulp `styles` tasks only looks at CSS files from source. It makes sense generally, however it also needs to look at the CSS files previously generated from the `sassStyles` task (which are already in the destination directory at that point) and process them further as expected.

I'm not sure how to best fix this bug - we could either reuse some code from here in the `sassStyles` task (so that that tasks handles the whole stack for Sass files, from parsing Sass up to resolving CSS vars), or we can adjust the `styles` task so that it also further processes intermediate CSS files previously generated from `sassStyles`. To me the first makes more sense, as that would allow to run `sassStyles` also individually and get the expected result.

@ataylorme Would be great to have your thoughts on this.

**Comment by ataylorme** [comment]
@felixarntz I did not consider this use case. I guess I assumed those switching to sass would use sass variables.

I think the best approach to allow CSS variables inside sass would be to run `postCSS` in the sass task after the sass plugin has transformed the sass files in the stream to CSS (but before the files are saved to the destination).

In this case I don't think it makes sense to keep two separate tasks in this case. I will make a PR with one task to rule them all*

*all being sass and CSS files.

**Comment by mor10** [comment]
@felixarntz #335 removes the `preserveVars` configuration entirely because PostCSS automatically creates fallbacks for CSS custom properties provided the `browserlist` setting is sufficiently low. The new default for WP Rig is to always use CSS custom properties with fallbacks rather than always transform. Because PostCSS kicks in after the Sass process, this should remove the problem you've outlined entirely I think. Can you test with this PR?
