### ISSUE TITLE
Is stylelint-disable necessary?

### ISSUE THREAD

**Issue by ataylorme** [wprig/wprig#359]
There is `stylelint-disable` in quite a few places of the source CSS files. I tried to hunt down the source (see [this comment](https://github.com/wprig/wprig/pull/356#issuecomment-469440345)) but was unable to do so.

@mor10 any idea why these were added or if they are still needed?

**Comment by mor10** [comment]
They were added by me, because Stylelint has issues with things it shouldn't have issues with, especially when it comes to nested selectors etc. It's a WordPress thing more than a Stylelint thing. It might be worth it to remove them all and see how many errors show up. It's been a while since they were added, so it's possible things have changed.

**Comment by mor10** [comment]
This is the kind of stuff that happens when you take out the `/* stylelint-disable */` rules. Not exactly sure why this happens, but it looks as if Stylelint doesn't fully understand selectors with hyphens in them and therefore thinks `.comment-content` and `.comment-meta` are in a parent-child relationship when in reality they are siblings.

![screen shot 2019-03-04 at 4 19 08 pm](https://user-images.githubusercontent.com/1132200/53771976-85f73580-3e99-11e9-8eaf-ea881f674b12.png)

**Comment by ataylorme** [comment]
@mor10 I think we can just [exclude that rule in the `gulp-phpcs` config](https://www.npmjs.com/package/gulp-phpcs#optionsexclude).

A better option though is probably to update `phpcs.xml.dist` to exclude that rule, rather than hard-code the exclude in gulp config when we have a configuration file for PHPCS.

**Comment by benoitchantre** [comment]
In #447, I have removed useless comments to disable stylelint.

Comments that are still in place are needed when:

- `no-descending-specificity` can safely be ignored
- duplicate selectors are used and cannot be avoided (eg. elements declared in `reset.css` that a declared again in `_elements.css`
- warnings are reported for no valid reason (eg. font family of one word without quotemarks)

**Comment by benoitchantre** [comment]
@ataylorme Can we close this issue?

#447 has been merged and removes unneeded stylelint comments.
