### ISSUE TITLE
How to add new tasks to Gulp

### ISSUE THREAD

**Issue by joseph-farruggio** [wprig/wprig#372]
## Issue Overview

Leaving this issue after having a conversation with Andrew Taylor. I need an example or documentation on how to add additional tasks to the new Gulp setup. I'm trying to process tailwind.css and I have this running in WP Rig V1.x, but V2 looks so different.

Here's Tailwind's docs on the Gulp setup: 
https://tailwindcss.com/docs/installation/#4-process-your-css-with-tailwind

**Comment by ataylorme** [comment]
@joseph-farruggio do you need to create a new gulp task or add tailwind to the existing CSS process?

**Comment by andreibarbuta** [comment]
I second this, we need some docs, even if it's preliminary, before official documentation gets done. This is a major roadblock. For example I wanted to use gulp group media queries, not a big thing but it was a personal choice, lost 2 days trying to figured it out. I'm not very proficient in Javascript, yet, but with some docs or an example I could do it.

**Comment by ataylorme** [comment]
Hi @andreibarbuta,
Thank you for posting your experience. I can empathize with struggling to understand something new, especially when it is not well documented.

I hope you can understand our side as well. Version 2 is still in active development. Version 1 is the stable version. which is why the `master` branch still reflects V1.

We are working towards a beta release of v2. Once we are at that point, and things are more stable, we will work on documentation.

We do have [some gulp documentation in the Wiki](https://github.com/wprig/wprig/wiki/gulp-in-WP-Rig) but it does not cover modifying the gulp build process. That is not something all users will do. We hope to support it, but as I said, the build process is still being worked on. We are focused on stabilizing it before writing more docs.

All this being said, I will attempt to point you in the right direction.

I would recommend starting with the gulp documentation. [The quickstart guide](https://gulpjs.com/docs/en/getting-started/quick-start) is really good.

This [why use pump](https://github.com/gulpjs/gulp/tree/master/docs/why-use-pump) article explains why we are using `pump` instead of `pipe`, which was used in older versions of gulp.

The [gulp improvement issue](https://github.com/wprig/wprig/issues/35) also outlines some of the gulp related things that have changed since V1.

To create a new gulp task you will need to make a new file in the `gulp` directory. gulp tasks are JavaScript functions. Once your task is created in its own file, it can be imported into `gulpfile.babel.js`. From there, it can either be re-exported as-is or used with `series` and/or `parallel` in another gulp task that does multiple things. This is what the main WP Rig tasks do.

To modify an existing task, you will need to edit the corresponding file in the `gulp` directory. Each task, as I mentioned above, is a JavaScript function. Most will use an instance of `pump`. `pump` takes an array of items to process. These are the things that would normally be chained together with `pipe`.

`gulp/styles.js` has array for `beforeReplacement` and `afterReplacement`. They are concatenated together. The reason for this is that we want to run string replacement on the file contents when building for production.

Anyway, we have an array being fed to `pump`. To add items into the `styles` task you simply need to place them into the array at the location you want.

For tailwind.css specifically, it can be [processed with gulp and postcss](https://tailwindcss.com/docs/installation/#gulp), both of which we are using in V2.

You can see [postcss being used here](https://github.com/wprig/wprig/blob/b184418d6b9719b747fcdafec344e81b35ee7493/gulp/styles.js#L68:L74). The plugins being used are [imported at the top of the file](https://github.com/wprig/wprig/blob/b184418d6b9719b747fcdafec344e81b35ee7493/gulp/styles.js#L6:L9).

You will need to do something similar with tailwind. Start by doing `npm install --save-dev tailwindcss`. Then add `import tailwindcss from 'tailwindcss';` to the top of the file with the other imports.

After that, add it to the end of the `postcss` plugins array with `tailwindcss('./path/to/your/tailwind.js')`.

The path to `tailwind.js` will need to be adjusted. You can hardcode it by using the `rootPath` variable, which points to the WP Rig theme directory.

That would be something like

```js
tailwindcss(`${rootPath}/path/to/tailwind.js`)
``` 

So the new postcss section of `styles.js` would look like this:

```js
gulpPlugins.postcss([
	AtImport(),
	postcssCustomProperties(postcssCustomPropertiesOptions),
	postcssCustomMedia(postcssCustomMediaOptions),
	postcssPresetEnv({
		stage: 3
	}),
	tailwindcss(`${rootPath}/path/to/tailwind.js`)
]),
```

**Comment by mor10** [comment]
@ataylorme should this go in docs, or is this out of scope?

**Comment by ataylorme** [comment]
@mor10 it could go in docs but things have changed since this was written so it can't go in as-is. I am going to close this issue and create a new issue for creating a doc.
