### ISSUE TITLE
Latest v2.0 branch looks very different then v2.0-alpha release

### ISSUE THREAD

**Issue by LukaszJaro** [wprig/wprig#411]
Hi,

I recently started to use wp-rig v1, watched all of the well done tutorial videos at https://wprig.io/course/wprig_en/

With the help of the video tutorials I found v1 to be simple to use starter theme that was much more advanced then anything I ever used i.e, '_s'

Then I discovered the new wprig 2.0-alpha release, read that dev folder was removed and everything was moved up a level which seemed to simplify things even further.

However now I see the latest branch of 2.0 looks completely different, component based, namespaces and classes everywhere, doesn't look anything like the 1.0 or 2.0-alpha I was use to.

I think my question is, since I do not have a OOP background, should I stick to using v1?

Thanks.

**Comment by ataylorme** [comment]
> However now I see the latest branch of 2.0 looks completely different, component based, namespaces and classes everywhere, doesn't look anything like the 1.0 or 2.0-alpha I was use to.

Yes, `v2.0` is still a work in-progress though we released a beta version today.

> I think my question is, since I do not have a OOP background, should I stick to using v1?

We are still working on documentation (which is why we are at beta and not v2 stable) but @felixarntz has written a great article on the Wiki [PHP Architecture in WP Rig](https://github.com/wprig/wprig/wiki/PHP-Architecture-in-WP-Rig).

Check out that article and try to use the new OOP architecture. We need help testing the beta. If things are still confusing open an issue on where you are stuck. That will help us know what needs more documentation.

We also have [WP Rig office hours](https://twitter.com/wprigio/status/1087442800440999936) which are a great place to come chat.

**Comment by LukaszJaro** [comment]
Thanks @ataylorme, I will read over the docs when I get some time and try out the latest wp-rig 2.0, and go from there.
