### ISSUE TITLE
cssVariables.json not processed - debug help needed

### ISSUE THREAD

**Issue by mbootsman** [wprig/wprig#413]
I am using PHPStorm 2019.1, and believe I have met all prerequisites according to 
`npm run build` works and browsersync is connected.

When Looking at the generated css, I still see the css variable names in there.
Like: 
```
color: var(--global-font-color);
font-family: var(--global-font-family);
font-size: calc(var(--global-font-size) / 16)rem;
line-height: var(--global-font-line-height);
```

I cannot seem to find any logfile that describes the build process, to see where things go wrong. Any pointers to help me debug this are welcome. Thanks.

**Comment by ataylorme** [comment]
@mbootsman WP Rig `v2.0` uses PostCSS + Browerlist to determine what needs to be processed. Your CSS output is what is expected with the default `.browserlistrc` file. Chrome, Firefox, etc. can process CSS variables.

If you need to support other browsers try editing `.browserlistrc`. For example, adding a new line to that file with `IE 11`. If the browsers defined to not support CSS variables they will be processed instead of output as-is.

[`v2.0` beta 1](https://github.com/wprig/wprig/releases/tag/v2.0-beta.1) was also released today, so please test the latest version.

**Comment by ataylorme** [comment]
@mbootsman [`v2.0-beta1`](https://github.com/wprig/wprig/releases/tag/v2.0-beta.1) [uses a standard CSS file instead of a JSON file for custom properties](https://github.com/wprig/wprig/blob/v2.0/assets/css/src/_custom-properties.css). Can you test the latest beta and see if you still have issues?

**Comment by mbootsman** [comment]
> @mbootsman [`v2.0-beta1`](https://github.com/wprig/wprig/releases/tag/v2.0-beta.1) [uses a standard CSS file instead of a JSON file for custom properties](https://github.com/wprig/wprig/blob/v2.0/assets/css/src/_custom-properties.css). Can you test the latest beta and see if you still have issues?

I will as soon as I can. What is the best way to update? Just do a git pull?

**Comment by ataylorme** [comment]
> What is the best way to update? Just do a git pull?

Depending on how much you modified `git pull` may have some merge conflicts. The alternative would be to do a fresh clone of the WP Rig repo and start there, optionally copying over files you modified.
