### ISSUE TITLE
Tip: Fade-in lazy-loaded images using CSS

### ISSUE THREAD

**Issue by digisavvy** [wprig/wprig#625]
## Tip
Fade-in lazy-loaded images using CSS

```
/* Sets opacity of images with class lazy, which allows us to use transition to fade image in when lazy class gets removed. */
img.lazy {
    opacity: 0;
    transition: all 550ms ease-in-out;
	
}

img {
	opacity: 1;
	transition: all 550ms ease-in-out;
}
```

**Comment by alexwcoleman** [comment]
Hello! Apologies for the delay. WP Rig is going through some minor restructuring.
This isn't an issue _per se_, but it is a good idea and (as you demonstrated) easy to implement in your project. WP Rig will be removing the Lazy Load because that is a part of WP 5.5. [Here's the notice I came across](https://make.wordpress.org/core/2020/04/08/lazy-loading-of-images-is-in-core/).
