### ISSUE TITLE
Using Font Awesome in WP Rig

### ISSUE THREAD

**Issue by mark60480** [wprig/wprig#650]
Can someone please get me detailed instructions on how to enqueue Font Awesome?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by drozumek** [comment]
In folder "assets" create folder named for example "fonts" and put there FA files (for example woff files). Then in "assets" > "css" > "src" folder create css file or add to global.css rule similar to this

@font-face {
	font-family: 'fa';
	src: url('../fonts/font-awesome.woff') format('woff');
	font-weight: normal;
	font-style: normal;
	font-display: block;
}

and other css rules which comes with FA pack.

But since Font Awesome 6 it has Wordpress plugin, so just request beta access to font awesome 6 and install plugin and you are ready to go.

**Comment by jacklowrie** [comment]
You can also enqueue it from the Styles component. add it to the `action_enqueue_styles()` method:
```php
// Enqueue Font Awesome.
$fontawesome_kit_link; //your kit link (you'll need to sign up at fontawesome.com)
wp_enqueue_script( 'font-awesome-kit', $fontawesome_it_link, [], null, false ); // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion

```

**Comment by mark60480** [comment]
Jack, thanks so much for this. However, it's not working for me. Probably because of my lack of coding skills. Please see attached screen shot and let me know what I"m doing wrong.
![FA_enqueue](https://user-images.githubusercontent.com/23484360/89350479-be460900-d675-11ea-9255-d816c02f2e8f.jpg)

**Comment by bleenwithcream** [comment]
> Jack, thanks so much for this. However, it's not working for me. Probably because of my lack of coding skills. Please see attached screen shot and let me know what I"m doing wrong.
> ![FA_enqueue](https://user-images.githubusercontent.com/23484360/89350479-be460900-d675-11ea-9255-d816c02f2e8f.jpg)

Just curious, after using enqueue to source the library. How are you implementing it's use?

**Comment by jacklowrie** [comment]
@mark60480 using developer tools in the browser, you can verify that font-awesome is being enqueued correctly in the header on whatever page you're using it on. It should look something like this:
```html
<script type="text/javascript" src="https://kit.fontawesome.com/[your-kit].js"></script>
```
If you see it (and your kit is set up correctly) you should be able to add icons in the body of the page using classes:
```html
<span class="fas fa-sun"></span>
<span class="fab fa-font-awesome-flag"></span>
```
If you see it enqueued correctly, then the issue is likely with how you're using font-awesome on the page (or set up your kit). double-check your kit, that the kit link is copied correctly, that there aren't typos in the classnames on the span (or other element) you're using it on, etc.

I'm not much help beyond getting font-awesome enqueued correctly, so if this doesn't work I recommend checking the [font-awesome docs](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use) for some insight on how to use it the way you need. Hope this helps.

**Comment by mark60480** [comment]
Jack, the main problem here is that I get this error message after adding the code:

Parse error: syntax error, unexpected 'wp_enqueue_script' (T_STRING) in /Volumes/Web Sites/Local Sites/sbp-2020-local/app/public/wp-content/themes/wprig-master/inc/Styles/Component.php on line 109

Could this be because I'm calling for an enqueue script in an area for enqueueing styles? Again, I apologize for my lack of coding skills.

**Comment by jacklowrie** [comment]
@mark60480 Looks like you're missing a semicolon on line 108. That should fix it.

**Comment by mark60480** [comment]
That worked! Here is the final code:

// Enqueue Font Awesome.
		wp_enqueue_script('font-awesome-kit', 'https://kit.fontawesome.com/myfontawsomekit.js', [], null, false); // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
