### ISSUE TITLE
How to move dropdown-symbol inside the '<a>' tag in navigation?

### ISSUE THREAD

**Issue by Hujjat** [wprig/wprig#78]
## Issue Overview

How can I customize the navigation and drop-down-menus? Currently, the symbol icon or the toggle-button for drop down is outside "<a>" tag in the link. 

![screen shot 2018-08-08 at 11 31 06 am](https://user-images.githubusercontent.com/5115878/43811175-9d429aca-9afe-11e8-8635-54f0afbab7eb.png)

this makes problem on mobile menu. I mean the symbol shift to the right and the menu at left. It makes it hard to position it right beside the drop-down item. 

Overall, I want to customize the navigation structure. where I can I change all those behaviours. 

Thank you :)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mor10** [comment]
The drop-down symbol is separate from the anchor element because it serves a different function than the anchor. You can use CSS to control exactly where the symbol appears in relation to the anchor because they both sit inside the `<li class="menu-item">` element. This is where it's currently styled: https://github.com/wprig/wprig/blob/master/dev/style.css#L897-L954

**Comment by bamadesigner** [comment]
What @mor10 said. The dropdown symbol is purposefully located to make the menu accessible. I would advise against changing the markup or behavior to allow the menu to remain accessible to those who don't use a mouse, but feel free to change the look and feel with CSS.

**Comment by Hujjat** [comment]
Awesome, I did the same, thank you
