### ISSUE TITLE
Lazy Loading Makes Custom Logo Invisible Until Scroll

### ISSUE THREAD

**Issue by joseph-farruggio** [wprig/wprig#82]
## Issue Overview

Note: I'm only experiencing this issue on safari / iOS

Lazy Loading is preventing the custom logo from being displayed in the site header. In its place, you'll see extra vertical white space. Once you scroll, the logo appears and the header adjusts to the appropriate size.

## Steps to Reproduce

1. Ensure Lazy Loading is enabled
2. Replace your site title with a custom logo
3. View your site on iOS

**Comment by mor10** [comment]
Needs further investigation. Likely culprit is how the lazy-loading script is told to ignore the site logo element.

**Comment by hazephase** [comment]
I have the same issue

**Comment by eddiepantoja** [comment]
This issue exists in IE as well. Thanks for all your hard work.

**Comment by tessak22** [comment]
Also had this same issue, and my "Menu" link to open the mobile menu also wouldn't work. I disabled lazy loading and that seemed to resolve both issues. The menu thing was absolutely bananas because at some times, the menu would work, even when lazy loading was on, but most of the time it wouldn't work. I do not need lazy loading for this site as it's not overly image-heavy but something to note. :)

**Comment by mor10** [comment]
This was on the V2 branch? Warrants further investigation.

**Comment by mor10** [comment]
Closed via #198
