### ISSUE TITLE
How to support fonts?

### ISSUE THREAD

**Issue by shangdev** [wprig/wprig#90]
I have use fontawesome4,7, it contains fonts file, It seems that he is not supported.

How resloved?

**Comment by mor10** [comment]
How are you currently adding in Fontawesome? JavaScript? CSS?

**Comment by shangdev** [comment]
By CSS.
And I created a new fonts folder in the dev directory.

**Comment by mor10** [comment]
The easiest way to add Fontawesome fonts is to enqueue the fontawesome stylesheet (from CDN or bundled in the theme) and reference it using regular CSS. Look at how other stylesheets are enqueued in functions.php to get an idea of how to do this.

**Comment by SimonIMG** [comment]
In case this helps someone, I want to use the _Avenir Next_ variable font. I have a `.ttf` file in a `dev/fonts folder`, then I updated the Project paths (starting at line 40) in `gulp.babel.js` file with the following...

```
fonts: {
	src: ["dev/fonts/*.{ttf,otf,woff,woff2}", "!dev/optional/**/*.*"],
	dest: "./"
},
```
So the full Project paths block looks like this...

```
// Project paths
const paths = {
	config: {
		cssVars: "./dev/config/cssVariables.json",
		themeConfig: "./dev/config/themeConfig.js"
	},
	php: {
		src: ["dev/**/*.php", "!dev/optional/**/*.*"],
		dest: "./"
	},
	styles: {
		src: ["dev/**/*.css", "!dev/optional/**/*.*"],
		dest: "./",
		sass: ["dev/**/*.scss"]
	},
	scripts: {
		src: [
			"dev/**/*.js",
			"!dev/**/*.min.js",
			"!dev/js/libs/**/*.js",
			"!dev/optional/**/*.*",
			"!dev/config/**/*"
		],
		min: "dev/**/*.min.js",
		dest: "./",
		libs: "dev/js/libs/**/*.js",
		libsDest: "./js/libs/",
		verboseLibsDest: "./verbose/js/libs/"
	},
	images: {
		src: ["dev/**/*.{jpg,JPG,png,svg,gif,GIF}", "!dev/optional/**/*.*"],
		dest: "./"
	},
	fonts: {
		src: ["dev/fonts/*.{ttf,otf,woff,woff2}", "!dev/optional/**/*.*"],
		dest: "./"
	},
	languages: {
		src: ["./**/*.php", "!dev/**/*.php", "!verbose/**/*.php"],
		dest: "./languages/" + config.theme.slug + ".pot"
	},
	verbose: "./verbose/",
	export: {
		src: [
			"**/*",
			"!" + config.theme.slug,
			"!" + config.theme.slug + "/**/*",
			"!dev/**/*",
			"!node_modules",
			"!node_modules/**/*",
			"!vendor",
			"!vendor/**/*",
			"!.*",
			"!composer.*",
			"!gulpfile.*",
			"!package*.*",
			"!phpcs.*",
			"!*.zip"
		],
		dest: "./"
	}
};
```

**Comment by jeanloup** [comment]
@mor10 WP-Rig must have changed quite a bit since this thread was opened. I'm trying to integrate FontAwesome 5 into my template but even though it's supposed to be a simple case of inserting a <script> tag in the header with an src of the form "https://kit.fontawesome.com/[hash].js", if I just add it to the header.php file I get the compiler telling me "Scripts must be registered/enqueued via wp_enqueue_script"

Neither the /functions.php nor the /inc/functions.php have enqueued Stylesheets in them so I'm at a loss how to do this seemingly simple task correctly.

Is it simpler to just download the stylesheet and treat is as any other custom stylesheet? Can you add anything via CDN with WP-Rig?

**Comment by leanderlindahl** [comment]
@jeanloup To include a fontawesome kit:
Open inc/Styles/Component.php and at approximately line 107 (after google fonts) add this:
```
// Enqueue Font Awesome Fonts.
wp_enqueue_style( 'font-awesome-kit', 'https://kit.fontawesome.com/[hash].js', [], null ); // phpcs:ignore WordPress.WP.EnqueuedResourceParameters.MissingVersion
```
Then your style will be included globally.

**Comment by jeanloup** [comment]
@leanderlindahl Thanks for this, unfortunately because it's supposed to be called via script as the kit is a javascript file, it confuses the browser. I get a "Resource interpreted as Stylesheet but transferred with MIME type text/javascript". Does Wordpress has a wp_enqueue_script() call by any chance?

**Comment by leanderlindahl** [comment]
@jeanloup Well that's embarrasing... I was a bit to quick there... If you add this instead it should work.

`wp_enqueue_script( 'font-awesome-kit', 'https://kit.fontawesome.com/[hash].js', array(), null, false );`

**Comment by jeanloup** [comment]
@leanderlindahl that's alright, you put me in the right direction that's all that matters and for that I'm very grateful thank you. :)
